### ISSUE TITLE
Image size ratio

### ISSUE THREAD

**Issue by johnbillion** [crstauf/query-monitor-extend#1]
Feature request of my own. I'd like to see the size ratio for each image size. For example:

```
 Name            | Width | Height | Ratio | Built-in
-----------------+-------+--------+-------+----------
 landscape-large | 300   | 200    | 3:2   |
```

You can calculate a ratio by using the greatest common denominator:

``` php
/**
 * Find the greatest common denominator between two numbers.
 *
 * @param  float $num1 First number.
 * @param  float $num2 Second number.
 * @return float       The GCD.
 */
protected static function gcd( $num1, $num2 ) {
    while ( $num2 != 0 ){
        $t    = $num1 % $num2;
        $num1 = $num2;
        $num2 = $t;
    }

    return $num1;
}

$gcd          = self::gcd( $width, $height );
$width_ratio  = $width / $gcd;
$height_ratio = $height / $gcd;
$image_ratio  = "{$width_ratio}:{$height_ratio}";
```

Disclaimer: I _may_ add the display of image sizes to QM itself, I'm not sure yet.

Ref: https://github.com/johnbillion/query-monitor/issues/196

**Comment by crstauf** [comment]
nice! made my work easy! :-)

what do you think should happen in the case of prime numbers?
do you think it's necessary to show the ratio if one of the numbers is prime?
(http://www.primos.mat.br/primeiros_10000_primos.txt)

![screen shot 2016-07-22 at 11 27 42 pm](https://cloud.githubusercontent.com/assets/4573033/17075532/f2ba278a-5063-11e6-8cbc-c9c2b74d7d72.png)

and I'll keep an eye out, and remove from QMX if/when necessary. 👍

**Comment by crstauf** [comment]
@johnbillion added the ratio column on [553bc89](https://github.com/crstauf/query-monitor-extend/commit/553bc896299c2e87125438caaccba00ec332e440) on the `reorganize` branch. please try it out and let me know what you think.

**Comment by johnbillion** [comment]
I think the current display is fine, if an image size includes a prime number then its ratio is simply `width:height`.
