### ISSUE TITLE
ACF Collector

### ISSUE THREAD

**Issue by crstauf** [crstauf/query-monitor-extend#10]

**Comment by wpsumo** [comment]
+1  https://github.com/johnbillion/query-monitor/issues/566

**Comment by wpsumo** [comment]
@crstauf Seems to give some php notices.

```
Notice | Undefined offset: 0 | 1 |
wp-content/plugins/query-monitor-extend-master/collectors/acf.php:88 | Plugin: query-monitor-extend-master

Notice | Trying to access array offset on value of type null | 1 | 
wp-content/plugins/query-monitor-extend-master/collectors/acf.php:118 | Plugin: query-monitor-extend-master

```

**Comment by crstauf** [comment]
@wpsumo Can you please open an issue and provide steps and fields to reproduce?

**Comment by wpsumo** [comment]
Nothing, just installed the latest version. Did you look at row 88 and 118 in acf.php?

**Comment by crstauf** [comment]
@wpsumo Please open a separate issue with steps and fields to reproduce the notices.
