### ISSUE TITLE
Conflict with Query Monitor Version 3.3.4

### ISSUE THREAD

**Issue by StfA76** [crstauf/query-monitor-extend#12]
Hi,
It seems there is a conflict with Query Monitor's latest version.
I have to deactivate "Query Monitor Extend" in order to see all the information available in the admin bar : https://ibb.co/0ZGGvjZ
As soon as I reactivate "Query Monitor Extend", nothing is displayed anymore : https://ibb.co/6WBrP89

Versions :
- WordPress 5.1.1
- Query Monitor : 3.3.4
- Query Monitor Extend : 0.0.5

Thanks for your help.
Best regards,
Stephane.

**Comment by crstauf** [comment]
@StfA76 Please update to the latest version of QMX: 1.0.

**Comment by StfA76** [comment]
Hello @crstauf,
Thanks a lot for the update.
Everything's working fine now.
Sorry for the trouble.

**Comment by crstauf** [comment]
No worries. 😄
