### ISSUE TITLE
Post autosave not working anymore

### ISSUE THREAD

**Issue by StfA76** [crstauf/query-monitor-extend#14]
Hi @crstauf ,

I've just find out the following issue.

How to reproduce?

- Install a brand new wordpress website (right now, it is 5.2.2).
- Add "Classic Editor" plugin + Active the plugin
- Add "Query Monitor" plugin + Active the plugin
- Set WP Writing rules as follow:
=> Default editor for all users = Classic Editor
=> Allow users to switch editors = Yes
- Create a new user with the role "Editor"
- Login with the newly created editor user
- Begin writing a new post using the classic editor => the post will be auto-saved every 60 seconds (the default value for WP autosaving).
- Save your draft article and exit editing.
- Add "Query Monitor Extend" plugin + Active the plugin
- Continue editing your previous post (with the editor user) using the classic editor => the post will not be auto-saved anymore.
- Try editing the post with the administrator user => the post will be auto-saved.

I also tried editing the post (with the editor user) with the new Guttenberg editor and the autosave seems to be working just fine in that case.

So it seems that the classic editor is the only one being affected here where you're connected with a user that do not have the Administrator role.

I hope this will help.

Best regards,
Stephane.

**Comment by crstauf** [comment]
Thanks for the report, @StfA76; fixed.
