### ISSUE TITLE
PHP Fatal error:  Uncaught Error: Class 'QM_Plugin' not found

### ISSUE THREAD

**Issue by ashucg** [crstauf/query-monitor-extend#16]
This error is caused if someone deactivates **Query Monitor** plugin. There must be a conditional block that checks whether **Query Monitor** plugin is active or **QM_Plugin** class exists before trying to extend the plugin/class to prevent the fatal error. If **Query Monitor** is not activate or class isn't found, an admin notice saying that this plugin requires **Query Monitor** should be displayed.

**Comment by crstauf** [comment]
@ashucg Thanks for the report; fixed.
