### ISSUE TITLE
image_sizes.php notice

### ISSUE THREAD

**Issue by kkmuffme** [crstauf/query-monitor-extend#17]
image_sizes.php has the sizes hardcoded (line 14-43)
in cases where a specific size doesn't exist, this will cause a PHP notice.

e.g. a WP page I work on doesnt have the medium_large size, causing errors all the time.

Please make this an apply_filters, so people can filter out or add any additional sizes they want to avoid getting notices.

**Comment by crstauf** [comment]
Thanks for the report, @kkmuffme.

**Comment by crstauf** [comment]
A result of QMX running on an old version of WordPress ([<4.4](https://make.wordpress.org/core/2015/11/10/responsive-images-in-wordpress-4-4/));`remove_image_size()` cannot be used to remove built-in image sizes.
