### ISSUE TITLE
Not working with Query monitor Version 3.6.5

### ISSUE THREAD

**Issue by Firiks** [crstauf/query-monitor-extend#19]
Stopped working when upgraded to Query monitor Version 3.6.5
![image](https://user-images.githubusercontent.com/23382187/99144469-75372500-2666-11eb-850d-e8fed992fda4.png)

**Comment by crstauf** [comment]
Thanks for the report, @Firiks. Will investigate tomorrow.

**Comment by crstauf** [comment]
Unfortunately I was required elsewhere today, and didn't have a chance to investigate. Probably Tuesday at this point. 😞

**Comment by crstauf** [comment]
@Firiks Fixed in a06acf3c818d28af97a66a1284156b0fd837f744.
