### ISSUE TITLE
Breaks Customizer

### ISSUE THREAD

**Issue by ihorvorotnov** [crstauf/query-monitor-extend#2]
With QM Extend active Customizer does not work - just a blank screen on the right, no Customizer sections on the left except the header with theme name. Turning QME off brings Customizer back immediately.

Tested on 4.6.* and 4.7 nightly

**Comment by crstauf** [comment]
Thanks for the report, Ihor. What version of WordPress did you experience
this issue with?

**Comment by ihorvorotnov** [comment]
> Tested on 4.6.* and 4.7 nightly

**Comment by crstauf** [comment]
@ihorvorotnov commit 5f3fe53 fixes issue.. please confirm.

**Comment by ihorvorotnov** [comment]
Confirmed, works fine. Thanks! 👍
