### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by Mte90** [crstauf/query-monitor-extend#20]
It is not clear the purpose of this plugin as there is no readme

**Comment by crstauf** [comment]
Would be glad to receive a pull request.

Ideally the following:
- link to [Query Monitor](https://github.com/johnbillion/query-monitor)
- list of tabs added by QMX
- how to use the `qmx_dump()` function

**Comment by Mte90** [comment]
Well a pull request is possible if I know what the plugin does. As there is no readme I never tried it as I have no idea what is the purpose :-)

**Comment by crstauf** [comment]
Sorry @Mte90, wasn't suggesting that _you_ should submit a pull request, was just noting on the issue that I'd welcome a PR and a few things I'd like to see.

For now, the repository's description will have to do:

> WordPress plugin with customizations to enhance/extend the already awesome Query Monitor plugin

**Comment by jamiolee** [comment]
How do I used this plugin? There's no instructions.

**Comment by crstauf** [comment]
@jamiolee Download from GitHub, and install thru the WordPress admin, similar to other plugins.

https://www.wpbeginner.com/beginners-guide/step-by-step-guide-to-install-a-wordpress-plugin-for-beginners/

(follow the "Install a Plugin using the WordPress Admin Plugin Upload" section)

**Comment by jevgen** [comment]
If you download to ZIP the plugin code - it will not activate and die with message "No correct plugin header".

**Comment by crstauf** [comment]
@jevgen Created issue #57 for you.
