### ISSUE TITLE
Parse error line 47

### ISSUE THREAD

**Issue by alewolf** [crstauf/query-monitor-extend#24]
I'm getting the following error when trying to activate the plugin: 

Parse error: syntax error, unexpected ')' in /Users/user/dev/apps/wordpress/wp-content/plugins/query-monitor-extend-master/query-monitor-extend.php on line 47

But, your code looks ok to me...

**Comment by crstauf** [comment]
Ahhh there's a comma at the end of line 46 that's causing the issue. Thanks for the report.
