### ISSUE TITLE
Fatal error with QM 3.0

### ISSUE THREAD

**Issue by johnbillion** [crstauf/query-monitor-extend#3]
Query Monitor Extend triggers a fatal error in the Scripts panel in QM 3.0:

```
Fatal error: Uncaught Error: Call to undefined method QMX_Output_Html_Assets::get_dependents() in wp-content/plugins/query-monitor-extend/output/assets.php on line 145
```

This is because I've moved some of the methods out of the output class and into the collector class. Sorry about that, but I can't really maintain backwards compatibility for something that's I'm not really expecting other plugins to extend.

**Comment by crstauf** [comment]
Understood, @johnbillion, and appreciate the context. I'll get a fix for this out tonight.

**Comment by crstauf** [comment]
Fix: https://github.com/crstauf/query-monitor-extend/commit/4cb03135abb5d1069829f53356a0adc2637294f6.
