### ISSUE TITLE
php warning in image_sizes collector when size is passed as array to filter__wp_get_attachment_image_src

### ISSUE THREAD

**Issue by beast099** [crstauf/query-monitor-extend#30]
php 7.4.6
wordpress 5.7.2

the $size parameter can be passed as an array to the 'wp_get_attachment_image_src' filter hook.  This throws a php warning in filter__wp_get_attachment_image_src

the Wordpress function [get_site_icon_url](https://developer.wordpress.org/reference/functions/get_site_icon_url/) is an example that can pass $size as an array.

`PHP Warning:  array_key_exists(): The first argument should be either a string or an integer in /var/www/html/dev.website.com/wp-content/plugins/query-monitor-extend-version-1.2/collectors/image_sizes.php on line 127
`

backtrace:
```
    wp-content/plugins/query-monitor-extend-version-1.2/collectors/image_sizes.php:127
       apply_filters('wp_get_attachment_image_src')
    wp-includes/media.php:991
        wp_get_attachment_image_src()
    wp-includes/media.php:1131
        wp_get_attachment_image_url()
    wp-includes/general-template.php:936
        get_site_icon_url()
    wp-includes/general-template.php:3222
        wp_site_icon()
    wp-includes/class-wp-hook.php:292
        do_action('wp_head')
    wp-includes/general-template.php:3009
        wp_head()
    wp-content/themes/Total/header.php:19
        load_template('wp-content/themes/Total/header.php')
    wp-includes/template.php:676
        locate_template()
    wp-includes/general-template.php:48
        get_header()
    wp-content/themes/Total/page.php:13
```
QM debug log of parameters passed to filter__wp_get_attachment_image_src when php warning is triggered
```
Array
(
    [image] => Array
        (
            [0] => https://dev.website.com/wp-content/uploads/2018/08/logo_512x512_square-32x32.jpg
            [1] => 32
            [2] => 32
            [3] => 1
        )

    [attachment_id] => 119
    [size] => Array
        (
            [0] => 32
            [1] => 32
        )

)
```

**Comment by morvy** [comment]
I just added another check on line 127: `if ( is_array($size) || !array_key_exists( $size, $this->data['sizes'] ) )`

As these "array sizes" are not registered, skipping this size is what I need.

**Comment by beast099** [comment]
@morvy I tested your revision and it works beautifully.  No more php warnings.

```	
        function filter__wp_get_attachment_image_src( $image, $attachment_id, $size ) {
		if ( is_array($size) || !array_key_exists( $size, $this->data['sizes'] ) )
			return $image;

		$this->data['sizes'][ $size ]['used']++;

		return $image;
	}
```

As far as I can tell looking at the docs,  the only use case in which Wordpress passes an array for the image size is when it's pulling a site's favicon icon image, so your solution makes sense.  good work and thanks for the fix.
