### ISSUE TITLE
PHP Error - Array_key_exists

### ISSUE THREAD

**Issue by mikeysouthwell** [crstauf/query-monitor-extend#31]
I have just installed the query_montior extended plugin and I am getting this php error in the query monitor logs:

Warning
Message:
array_key_exists(): The first argument should be either a string or an integer
Count: 4
Location: wp-content/plugins/query-monitor-extend-master/collectors/image_sizes.php:127 
Component: 
Plugin: query-monitor-extend-master

Can you please take a look?

**Comment by crstauf** [comment]
Possible duplicate of #30.

**Comment by mikeysouthwell** [comment]
Hi crstauf,

Thank you for the prompt response. 

I have implemented the fix suggested in the link you provided and this has resolved the issue.
