### ISSUE TITLE
Query Monitor Extend V.1.2 makes a .php warning:

### ISSUE THREAD

**Issue by GodCodesGuru** [crstauf/query-monitor-extend#36]
Hi Caleb,

below you can find a full copy of Query Monitor's message (there are no other tips to paste here for replication. I've just updated v.1.1 to v. 1.2. and got this message (I'm running the WP version 5.8.1 and 7.3.32 .php version. Thanks.

<html>
<body>

Warning | array_key_exists(): The first argument should be either a string or an integer | 4 | -wp-content/plugins/query-monitor-extend-version-1.2/collectors/image_sizes.php:127array_key_exists()wp-content/plugins/query-monitor-extend-version-1.2/collectors/image_sizes.php:127apply_filters('wp_get_attachment_image_src')wp-includes/media.php:991wp_get_attachment_image_src()wp-includes/media.php:1131wp_get_attachment_image_url()wp-includes/general-template.php:936get_site_icon_url()wp-includes/general-template.php:3228wp_site_icon()wp-includes/class-wp-hook.php:303do_action('admin_head')wp-admin/admin-header.php:147 | Plugin: query-monitor-extend-version-1.2
-- | -- | -- | -- | --

</body>
</html>

**Comment by GodCodesGuru** [comment]
Hi there,

today I've got more warnings. Maybe it could be helpful:

<html>
<body>


Warning | array_key_exists(): The first argument should be either a string or an integer | 5 | -wp-content/plugins/query-monitor-extend-version-1.2/collectors/image_sizes.php:127array_key_exists()wp-content/plugins/query-monitor-extend-version-1.2/collectors/image_sizes.php:127apply_filters('wp_get_attachment_image_src')wp-includes/media.php:991wp_get_attachment_image_src()wp-includes/media.php:1131wp_get_attachment_image_url()wp-includes/general-template.php:936get_site_icon_url()wp-content/plugins/seo-by-rank-math/includes/admin/metabox/class-screen.php:266RankMath\A\M\Screen->get_site_icon()wp-content/plugins/seo-by-rank-math/includes/admin/metabox/class-screen.php:145RankMath\A\M\Screen->get_values()wp-content/plugins/seo-by-rank-math/includes/admin/metabox/class-screen.php:106RankMath\A\M\Screen->localize()wp-content/plugins/seo-by-rank-math/includes/admin/metabox/class-metabox.php:77RankMath\A\M\Metabox->enqueue()wp-includes/class-wp-hook.php:303do_action_ref_array('rank_math/admin/enqueue_scripts')wp-content/plugins/seo-by-rank-math/includes/traits/class-hooker.php:88RankMath\A\Assets->do_action()wp-content/plugins/seo-by-rank-math/includes/admin/class-assets.php:162RankMath\A\Assets->enqueue()wp-includes/class-wp-hook.php:303do_action('admin_enqueue_scripts')wp-admin/admin-header.php:102 | Plugin: query-monitor-extend-version-1.2
-- | -- | -- | -- | --



</body>
</html>

PHP errors were triggered during an Ajax request. See your browser developer console for details.

GET https://godcodes.guru/wp-admin/post.php?post=6329&action=edit&classic-editor → 200

**Comment by crstauf** [comment]
@GodCodesGuru Will you please try branch `issue/35` and see if you continue to have this error?

**Comment by GodCodesGuru** [comment]
Hi Caleb,
Thanks for the reply.
I will try it but I don't understand what you mean.
What does it mean " to branch the issue/35"?
Thanks again.
GC
    Am Mittwoch, 29. Dezember 2021, 02:40:58 MEZ hat Caleb Stauffer ***@***.***> Folgendes geschrieben:  
 
 


@GodCodesGuru Will you please try branch issue/35 and see if you continue to have this error?

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by crstauf** [comment]
@GodCodesGuru Please use this link to download and extract the files to test with:

https://github.com/crstauf/query-monitor-extend/archive/refs/heads/issue/35.zip

**Comment by GodCodesGuru** [comment]
Hi Caleb,
thanks for the issue35. It seems to work without issues.
Happy New Year!
GC

    Am Mittwoch, 29. Dezember 2021, 04:37:40 MEZ hat Caleb Stauffer ***@***.***> Folgendes geschrieben:  
 
 


@GodCodesGuru Please use this link to download and extract the files to test with:

https://github.com/crstauf/query-monitor-extend/archive/refs/heads/issue/35.zip

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GodCodesGuru** [comment]
Hi Caleb,
I've just found this warning:
Warning: array_key_exists() expects parameter 2 to be array, null given in ----------- /godcodes.guru/wp-content/plugins/query-monitor-extend-issue-35/collectors/image_sizes.php on line 133

Please advise.
Thanks and happy New Year again.
    Am Donnerstag, 30. Dezember 2021, 19:02:59 MEZ hat Caleb Stauffer ***@***.***> Folgendes geschrieben:  
 
 


Closed #36.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by crstauf** [comment]
@GodCodesGuru That's a separate issue, probably a duplicate of #35; please review that issue and provide any additional, helpful, or valuable info there.

**Comment by GodCodesGuru** [comment]
This issue I've found because activated wp debug.  Nothing more, only php warning after activating. This issue is not shown by Query Monitor.

I think if you try to activate wp debug you will see it.

Thanks.

**Comment by kenny-nt** [comment]
> This issue I've found because activated wp debug. Nothing more, only php warning after activating. This issue is not shown by Query Monitor.
> 
> I think if you try to activate wp debug you will see it.
> 
> Thanks.

Exactly the same with my case, but will thrown a FATAL ERROR if using PHP8.
The issue just happen when no login.

```
[STDERR] PHP Fatal error: Uncaught TypeError: array_key_exists(): Argument #2 ($array) must be of type array, null given in /public_html/wp-content/plugins/query-monitor-extend/collectors/image_sizes.php:133
Stack trace:
#0 /public_html/wp-includes/class-wp-hook.php(305): QMX_Collector_Image_Sizes->filter__wp_get_attachment_image_src()
#1 /public_html/wp-includes/plugin.php(189): WP_Hook->apply_filters()
#2/public_html/wp-includes/media.php(991): apply_filters()
#3 /public_html/wp-includes/media.php(1131): wp_get_attachment_image_src()
#4 /public_html/wp-includes/general-template.php(936): wp_get_attachment_image_url()
#5 /public_html/wp-includes/general-template.php(977): get_site_icon_url()
#6 /public_html/wp-includes/general-template.php(3223): has_site_icon()
#7 /public_html/wp-includes/class-wp-hook.php(303): wp_site_icon()
#8 /public_html/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters()
#9 /public_html/wp-includes/plugin.php(470): WP_Hook->do_action()
#10 /public_html/wp-includes/general-template.php(3015): do_action()
#11 /public_html/wp-content/themes/flatsome/header.php(10): wp_head()
#12/public_html/wp-includes/template.php(770): require_once('...')
#13 /public_html/wp-includes/template.php(716): load_template()
#14 /public_html/wp-includes/general-template.php(48): locate_template()
#15 /public_html/wp-content/themes/flatsome/page-transparent-header-light.php(5): get_header()
#16 /public_html/wp-includes/template-loader.php(106): include('...')
#17 /public_html/wp-blog-header.php(19): require_once('...')
#18 /public_html/index.php(17): require('...')
#19 {main}
thrown in /public_html/wp-content/plugins/query-monitor-extend/collectors/image_sizes.php on line 133
```

Exactly the Fatal Error happen when Query Monitor update to 3.8.0. If Query Monitor version < 3.8.0, no fatal error.
