### ISSUE TITLE
Implement cease and detach functionality

### ISSUE THREAD

**Issue by crstauf** [crstauf/query-monitor-extend#43]
The new cease and detach feature was added in johnbillion/query-monitor#590. In `QM_Dispatcher::init()` there's a check if the user can view QM output, and if not, cease and detach:

https://github.com/johnbillion/query-monitor/blob/d5b622b91f18552e7105e62fa84d3102b08975a4/classes/Dispatcher.php#L128-L132

The `do_action( 'qm/cease' )` triggers the `QM_Collectors::cease()` function, which iterates over all the collectors and calls [`QM_Collector::discard_data()`](https://github.com/johnbillion/query-monitor/blob/d5b622b91f18552e7105e62fa84d3102b08975a4/classes/Collector.php#L162-L164), which causes the `data` property to become an empty array, and thus rendering the data array to not have an `assets` key.

**Comment by crstauf** [comment]
@khanh-nt Will you please try the `support-cease-feature` branch and let me know if you continue to have the fatal error?

**Comment by crstauf** [comment]
Going to proceed with merging this without @khanh-nt's confirmation.

**Comment by kenny-nt** [comment]
Sorry because of working hard last week. I have installed 'support-cease-feature' branch and seem it worked.
