### ISSUE TITLE
Support for QM 3.10

### ISSUE THREAD

**Issue by crstauf** [crstauf/query-monitor-extend#46]
```
PHP Fatal error:  Uncaught Error: Failed opening required '/output/Html.php' thrown in /wp-content/mu-plugins/qmx-constants-output.php on line 19
  ```

**Comment by kenny-nt** [comment]
Supported?

**Comment by crstauf** [comment]
@kenny-nt Not yet; that's what this issue is for.

**Comment by kenny-nt** [comment]
When will Query Monitor Extend support for QM 3.10?

**Comment by crstauf** [comment]
Apologies: I've forgotten it's currently incompatible. Unless something comes up, I'll start working on it this week.

**Comment by crstauf** [comment]
@kenny-nt Will you please try #47 to confirm compatibility with QM 3.10?

**Comment by kenny-nt** [comment]
> @kenny-nt Will you please try #47 to confirm compatibility with QM 3.10?

It is #46 right? I can not view any #47...
If it is #46 > Installed and there is no error anymore.

**Comment by crstauf** [comment]
@kenny-nt Sorry... yes, the branch is named issue/46... I was referring to the PR, #47.

Great! I'll get that merged next week.
