### ISSUE TITLE
count(): Parameter must be an array or an object that implements Countable

### ISSUE THREAD

**Issue by rorar** [crstauf/query-monitor-extend#58]
Query Monitor Outputs an issue whileQuery Monitor Extendis ac
**Warning**	
count(): Parameter must be an array or an object that implements Countable	

wp-content/plugins/query-monitor-extend-version-1.4.2/acf/qmx-acf-output.php:554
apply_filters('qm/output/panel_menus')
do_action('shutdown')
shutdown_action_hook()

Plugin: query-monitor-extend-version-1.4.2

**Comment by crstauf** [comment]
@rorar Thanks! Will you please try this branch?

https://github.com/crstauf/query-monitor-extend/tree/issue/58

**Comment by rorar** [comment]
I tried the branch - now QM ouputs the following errors:

Warning	
count(): Parameter must be an array or an object that implements Countable	
wp-content/plugins/query-monitor-extend-version-1.4.2/acf/qmx-acf-output.php:558
apply_filters('qm/output/panel_menus')
do_action('shutdown')
shutdown_action_hook()
1	Plugin: query-monitor-extend-version-1.4.2

Notice	
Undefined index: groups	
wp-content/plugins/query-monitor-extend-version-1.4.2/acf/qmx-acf-output.php:558
apply_filters('qm/output/panel_menus')
do_action('shutdown')
shutdown_action_hook()
1	Plugin: query-monitor-extend-version-1.4.2


Note: I renamed the plugin folder of the branch to match the previous one from the 1.4.2 release tag for an inplace upgrade

**Comment by crstauf** [comment]
@rorar Please try the branch again?

**Comment by crstauf** [comment]
@rorar Please try the branch again?

**Comment by rorar** [comment]
I tried. Uninstalled the plugin and re-installed it with the branch 58
Still Notice and Warning inside WP Debug Log:

```
[14-Jun-2023 08:27:07 UTC] PHP Notice:  Undefined index: groups in /var/www/example.com/htdocs/wp-content/plugins/query-monitor-extend-version-1.4.2/acf/qmx-acf-output.php on line 560
[14-Jun-2023 08:27:07 UTC] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/example.com/htdocs/wp-content/plugins/query-monitor-extend-version-1.4.2/acf/qmx-acf-output.php on line 560
```

**Comment by crstauf** [comment]
I cannot reproduce this: will need active investigation from you or someone else with the same problem to resolve.

**Comment by crstauf** [comment]
I cannot reproduce this: will need active investigation from @rorar or someone else with the same problem to resolve.

**Comment by crstauf** [comment]
@rorar I was able to reproduce this locally, and have pushed up a fix. Will you please try the branch to confirm?

**Comment by rorar** [comment]
I've seen that you've updated the master branch. Should I try the master branch or https://github.com/crstauf/query-monitor-extend/tree/issue/58 ?

**Comment by crstauf** [comment]
@rorar `issue/58` branch please.
