### ISSUE TITLE
Add ability to install via composer

### ISSUE THREAD

**Issue by chrillep** [crstauf/query-monitor-extend#65]

**Comment by mklepaczewski** [comment]
This is currently possible by adding GitHub repository:
```json
...
"repositories": [
    ...
    { "type": "vcs", "url": "https://github.com/crstauf/query-monitor-extend.git" }
    ...
]
```
and installing the package with dev stability:
```bash
composer require --dev crstauf/query-monitor-extend:@dev
# or, if you want specific commit
composer require --dev 'crstauf/query-monitor-extend:dev-master#5e11ab8af42b17c2e5a8fca656c421c8a2a6190e'
```
I don't know if it's possible to install the package using the version name. `query-monitor-extend` uses `version/<version>` tags, which aren't recognized by composer. 

@crstauf If I'm not mistaken, switching to `vX.Y.Z` tag format would allow users to install a specific version as the tags are recognized by composer.

**Note** #75 is required for this to work.

**Comment by crstauf** [comment]
Thanks, @mklepaczewski! Added tags with `vX.Y.Z` to the existing `version/X.Y.Z` tags, and will use `vX.Y.Z` moving forward.

That should be it, correct?

**Comment by mklepaczewski** [comment]
Yup, I just checked. It works:

```bash
mkdir test
cd test
composer init
composer config repositories.0 vcs "https://github.com/crstauf/query-monitor-extend.git"
composer require crstauf/query-monitor-extend:1.6.1
./composer.json has been updated
Running composer update crstauf/query-monitor-extend
Loading composer repositories with package information
Updating dependencies
Lock file operations: 1 install, 0 updates, 0 removals
  - Locking crstauf/query-monitor-extend (v1.6.1)
Writing lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
Generating autoload files
No security vulnerability advisories found
```

**Comment by crstauf** [comment]
Thanks!

**Comment by chrillep** [comment]
if you just log in to packigist you can add the package there.
https://packagist.org/packages/submit

So we dont have to add vcs. ( But ill create another ticket :) )

I dont want to add it as a vcs since it has to be done manually.


I can help with a pipeline but you need to do the initial setup.
This is DX comfort ❤️ 



to add a repo to composer.json you can run
```sh

composer config repositories.crstauf/query-monitor-extend vcs https://github.com/crstauf/query-monitor-extend.git

```

~~but you cant remove a repo with the composer config command :(~~
```sh
composer config --unset repositories.crstauf/query-monitor-extend
```

**Comment by chrillep** [comment]
and btw your ok (it works with composer) with semver tagging with Or without 'v' prefix
