### ISSUE TITLE
Make release possible without building custom ZIP archives

### ISSUE THREAD

**Issue by szepeviktor** [crstauf/query-monitor-extend#73]
![image](https://github.com/crstauf/query-monitor-extend/assets/952007/cd6acee9-7310-407a-acca-62eae55bb910)

The GitHub ZIP ("Source code") fie can be customized in `.gitattributes` by `export-ignore`-ing files/directories.
Could be checked with this command on POSIX systems: `git archive HEAD | tar -t`

Instructions for the MU installation could include

1. Download `mu-plugin/load-qmx.php` to your `mu-plugins` directory
2. Download the GitHub ZIP to your `mu-plugins` directory
3. Extract the ZIP archive in place then delete it
4. Done 🍏

What do you think?

**Comment by crstauf** [comment]
That's cool about `.gitattributes`; thanks for sharing.

I prefer the current approach: gives me full control, gives user easy choices without following directions, and keeps the source code available as a zip.
