### ISSUE TITLE
Improve Github docs for mu-plugin use

### ISSUE THREAD

**Issue by kkmuffme** [crstauf/query-monitor-extend#76]
Could you improve the documentation in the readme/Github page, for the mu-plugin:
Specifically:
- does query-monitor need to be placed in mu-plugins too?
- what happens if query-monitor is not activated, but query-monitor-extend is in mu-plugins?

**Comment by crstauf** [comment]
1. Query Monitor does not need to be in `mu-plugins` directory.
2. The files will be included, but none of the code will execute.

I'll consider adding to readme: I'm leaning towards no, but will think about it more.

**Comment by crstauf** [comment]
I have added links to demos to the readme in 1f04b031d33fd29e655a931113805482b2aa321c, which I prefer over including answers to these questions.
