### ISSUE TITLE
2 Warning in query monitor

### ISSUE THREAD

**Issue by amirhoseinsadeghi** [crstauf/query-monitor-extend#85]
include_once(/home/public_html/wp-content/plugins/query-monitor-extend/qmx-time-hooks.php): Failed to open stream: No such file or directory | wp-content/plugins/query-monitor-extend/query-monitor-extend.php:125

include_once(): Failed opening '/home/public_html/wp-content/plugins/query-monitor-extend/qmx-time-hooks.php' for inclusion (include_path='.:/opt/alt/php81/usr/share/pear:/opt/alt/php81/usr/share/php:/usr/share/pear:/usr/share/php')
wp-content/plugins/query-monitor-extend/query-monitor-extend.php:125

**Comment by crstauf** [comment]
@amirhoseinsadeghi Thank you! Please try [v1.6.3](https://github.com/crstauf/query-monitor-extend/releases/tag/v1.6.3).
